### PR TITLE
eslint  - standard linting for Javascript

### PR DESCRIPTION
**Pull request by Pushplaybang**
I've added a project level eslint file,  to lint against our js standards, be used for static analysis on new projects, eslint seems to be the defacto linter from my research, and it is compatible with sublime, VIM, phpStorm etc.

This has some dependencies that we need to provide locally.   This include ES5 and ES6 and catches errors as well as style issues, linting against the AirBnB standard.
## To Setup

``` sh
npm install
```

This gives us coverage for ES5, ES6, jsx and the airBnB standard as extended in the `.eslintrc`  - make sure you're using eslint for your editor / IDE.  you can easily select whether you're doing ES5 or ES6 by  changing the extension  ie.: `extends: airbnb/legacy` etc.  See the comments in the file.

### CODE REVIEW

**Comment by Pushplaybang** [comment]
added local deps for linting,, needs to be installed with NPM.  Thoughts @Nona-Creative/nonabots

**Comment by SkippyZA** [comment]
I feel this is getting a little to specific for a starter repo. If we start adding language specific dependencies, we are creating a ton of bloat.

From my experience, if I see a package.json file I run `npm install`. If I am in a PHP project, chances are I will still run it. Same goes for a default `composer.json` file in a Node project.

What we could really do is create a basic `global defaults` repo, the fork it for `php defaults`, `node defaults` etc. While this would reduce the amount of bloat, we now sit with having to manage a ton of boilerplate repos.

**Comment by SkippyZA** [comment]
As I think about it a little more, if we did go the convoluted way of a repo per language, we could register them on yeoman to make creating new projects super easy, but now we adding ANOTHER thing to manage

**Comment by Pushplaybang** [comment]
hey, yeah, I think it'd be easiest to distribute a bash file or something. 

As most, if not all our projects include javascript between the front-end / back-end depending, this is the linting dependancies nessecarry for linting ES5 / ES6 with our standard, that previously agreed to, so should be run straight off the bat, a you suggested you would imo.

**Comment by Pushplaybang** [comment]
Codeclimate will require the eslintrc file https://docs.codeclimate.com/docs/eslint  in order for it to run.

**Comment by ShaunEgan** [comment]
This is not applicable to all projects - don't think this repo is the right home for this.

**Comment by SkippyZA** [comment]
If we going to be using CodeClimate, then the client should be able to handle the linting based on the .eslintrc. We wont be needing the package.json file.

I am not against the linting spec, just against the default package.json

**Comment by Pushplaybang** [comment]
@ShaunEgan @SkippyZA, this would be applicable and appropriate for every project on our backlog currently for both teams as far as I can see.

**Comment by JamesGarethSmith** [comment]
I think you guys are talking about a specific issue here what's really at stake is a deeper disagreement: i.e how abstract should this repo be?

This repo is trying to be all things for all projects but I wonder if we might be better served by having a default repo per type of project (Meteor, Node, Rails etc.).

That way this repo could just contain all the things that are truly global to all projects.

**Comment by Pushplaybang** [comment]
@JamesGarethSmith  - yeah I think that's a possibility down the road.

I was aiming to keep this really slim
- github templates
- .gitignore
- contribution guidelines
- JS linting (as I can't think of a project with JS whether its meteor, or rails or WordPress)
  - this requires the .eslintrc and the package.json
- boilerplate code climate yml file.

There will of course be some setup but that should get us going pretty quickly and allows us to have some consistency from the get-go.

**Comment by SkippyZA** [comment]
I am still against the default package.json, especially if we moving to use CodeClimate

Other than that, I am happy to merge in and open any issues going forward.

**Comment by darrynten** [comment]
I'd like trailing commas please.

Can't tell you how many times I've added a line to an array, or changed the order of objects and wasted precious seconds on figuring out why it's broken only to eventually see that it's a missing trailing comma.

Controversial, I know, but once you keep trailing commas you'll wonder how you ever lived without them.

**Comment by SkippyZA** [comment]
I am 100% against trailing commas. I feel it is a bad practice and a lot of other languages will error if a trailing comma is added.

**Comment by ShaunEgan** [comment]
PHPStorm highlights lines in the editor which have problems or may cause potential issues. This is an invaluable tool in finding problems before a commit is even created. Trailing commas would just be another item highlighting even more lines, making the signal-to-noise ratio of that entire tool pretty terrible.

**Comment by Pushplaybang** [comment]
Hi Guys, 

this seems to have gone way off topic.  Regarding trailing commas, for JS the airBnB standard suggests trailing commas, and I'm a fan as well, but this is a standards conversation.  

The only argument against the package.json has been that it's not applicable to every project which  is simply not true.  The standardised linting will require the dependencies, and I really can't see a problem with the inclusion of package.json with the basic devDependancies defined.  

#### Reasons For:
- Standard linting across teams and projects for ES5 & ES6 requires it.
- Every project currently in production should require it, as well as every project we have in our pipeline currently, So it would be true to say we're optimising for the most common case, I would agree with you if we were talking about a composer.json etc, but I thin the case here is different. JS is universal in our work and it'll be an incredibly uncommon case were we need to remove it.
- Its incredibly easy to edit or remove should we ever need to

**Comment by Pushplaybang** [comment]
@ShaunEgan  - as a side note, using eslint in all our editors will give us consistency, so whether we agree on trailing commas or not or any other standards, it can be set in this configuration, and then everyone a) will see the same thing,  and b) will have parity with the static analysis tool,  helping to both teach and enforce our JS standards across the organisation easily.

**Comment by ShaunEgan** [comment]
Yes @Pushplaybang , I understand that.

**Comment by Pushplaybang** [comment]
@ShaunEgan  @SkippyZA are there any other reasons against?

**Comment by ShaunEgan** [comment]
No other reasons - Im still not a fan though.

**Comment by Pushplaybang** [comment]
okay, @darrynten  @JamesGarethSmith  - any reason against?

**Comment by JamesGarethSmith** [comment]
I'm happy for this to be merged.

**Pull request merged**
