### PR TITLE
fixed a few typos in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by JamesGarethSmith**
This was just a quick run through fixing some spelling errors and improving consistency.

@Pushplaybang There are a few grammar issues and sentences that could be rewritten to be more concise/readable. Let me know if you think that would be valuable and I'll push that up.

P.S. loving the irony that my commit message has a typo :laughing:

### CODE REVIEW

**Comment by Pushplaybang** [comment]
Awesome 👍   

yeah go wild, if there are other improvements  - let's have em! - maybe as second PR?

happy to merge, when you're ready.

**Comment by JamesGarethSmith** [comment]
@Pushplaybang Cool, yeah I'll do it as a second PR.

**Comment by Pushplaybang** [comment]
@JamesGarethSmith awesome.

**Comment by Pushplaybang** [comment]
related to #9

**Pull request merged**
